const funFacts = [
  "You can find me under the name Innygr on quite a few platforms",
  "The thing I use as a logo, is my OC!",
  "My OC is a Celestan, a fictional species of creatures",
  "My name is pronounced Inn-es",
  "My OC's name is NegInny(Neg-Inn-e), pretty close to my name eh?",
  "I have too many unfinished game-development projects (unrelated to class)",
  "I made the background of this website in Blender, which you already know...",
  "I made the End Crystal on this website with Three.js",
  "This website has an animated 3D object floating over it",
  "I like making games more than actually finishing them",
  "I have made projects in Construct, Roblox, and plain HTML/JavaScript",
  "I made Escape The Forsaken Realm",
  "I also have a bunch of game ideas that have never escaped the idea stage",
  "I tend to add random secrets to my projects",
  "I like putting references into my games",
  "I made my own Standard Galactic Alphabet font part of this website",
  "I have spent an unreasonable amount of time making things spin",
  "If something can have particles, I will probably add particles",
  "I apparently needed a 3D End Crystal on my GameDev assignment website",
  "The End Crystal was not necessary for this website",
  "I added it anyway",
  "I am currently running out of fun facts",
  "This is definitely not filler",
  "Okay, this one might be filler",
  "I have officially run out of interesting facts"
];
